spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@129.156.112.154:1521/PDB1.596094338.oraclecloud.internal
    username: gac
    password: Gac123456
    druid:
      initialSize: 1
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 20000
      minEvictableIdleTimeMillis: 40000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10
      remove-abandoned: true

mybatis:
  type-aliases-package: com.oracle.scc.demo.pojo
logging:
  level:
    com.oracle.scc.demo: debug